from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from sqlalchemy.orm import Session

from app.models.alert import Alert
from app.models.user import User
from app.services.audit_service import AuditService


class AlertReportServiceSimple:
    """Simplified PDF generation service for debugging"""

    @staticmethod
    def _safe(value: object) -> str:
        return escape(str(value if value is not None else "N/A"), quote=True)

    @classmethod
    def generate_incident_report(cls, *, db: Session, alert: Alert, generated_by: User) -> bytes:
        """Generate simple PDF incident report for an alert"""
        
        # Create audit log for report generation
        AuditService.create_audit_log(
            db=db,
            actor_user_id=generated_by.id,
            action="alert_incident_report_generated",
            entity_type="alert",
            entity_id=str(alert.id),
            details={
                "alert_id": alert.id,
                "generated_by_user_id": generated_by.id,
                "alert_severity": alert.severity,
                "alert_title": alert.title
            }
        )
        db.commit()
        
        # Create PDF buffer
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        
        # Get styles
        styles = getSampleStyleSheet()
        
        # Build simple PDF elements
        elements = []
        
        # Title
        elements.append(Paragraph("LogShield Alert Report", styles['Title']))
        elements.append(Spacer(1, 20))
        
        # Alert details
        elements.append(Paragraph(f"<b>Alert ID:</b> {cls._safe(alert.id)}", styles['Normal']))
        elements.append(Paragraph(f"<b>Title:</b> {cls._safe(alert.title)}", styles['Normal']))
        elements.append(Paragraph(f"<b>Severity:</b> {cls._safe(alert.severity)}", styles['Normal']))
        elements.append(Paragraph(f"<b>Status:</b> {cls._safe(alert.status)}", styles['Normal']))
        elements.append(Paragraph(f"<b>Risk Score:</b> {cls._safe(alert.risk_score)}", styles['Normal']))
        elements.append(Paragraph(f"<b>Created:</b> {alert.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}", styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Additional details
        if alert.detection_rule:
            elements.append(Paragraph(f"<b>Attack Type:</b> {cls._safe(alert.detection_rule.category)}", styles['Normal']))
            if alert.detection_rule.mitre_tactic:
                elements.append(Paragraph(f"<b>MITRE Tactic:</b> {cls._safe(alert.detection_rule.mitre_tactic)}", styles['Normal']))
            if alert.detection_rule.mitre_technique:
                elements.append(Paragraph(f"<b>MITRE Technique:</b> {cls._safe(alert.detection_rule.mitre_technique)}", styles['Normal']))
        
        if alert.assigned_to:
            elements.append(Paragraph(f"<b>Assigned To:</b> {cls._safe(alert.assigned_to.full_name)}", styles['Normal']))
        
        if alert.normalized_log:
            if alert.normalized_log.src_ip:
                elements.append(Paragraph(f"<b>Source IP:</b> {cls._safe(alert.normalized_log.src_ip)}", styles['Normal']))
            if alert.normalized_log.username:
                elements.append(Paragraph(f"<b>Username:</b> {cls._safe(alert.normalized_log.username)}", styles['Normal']))
        
        elements.append(Spacer(1, 20))
        elements.append(Paragraph(f"<b>Generated By:</b> {cls._safe(generated_by.full_name or generated_by.email)}", styles['Normal']))
        elements.append(Paragraph(f"<b>Generated At:</b> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}", styles['Normal']))
        
        # Build PDF
        try:
            doc.build(elements)
            # Get PDF bytes
            pdf_bytes = buffer.getvalue()
            buffer.close()
            return pdf_bytes
        except Exception as e:
            # If PDF generation fails, return a simple text-based PDF
            buffer.close()
            return cls._generate_fallback_pdf(alert, generated_by)
    
    @staticmethod
    def _generate_fallback_pdf(alert: Alert, generated_by: User) -> bytes:
        """Generate a fallback PDF if reportlab fails"""
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        lines = [
            "LogShield Alert Report",
            f"Alert ID: {alert.id}",
            f"Title: {alert.title}",
            f"Severity: {alert.severity}",
            f"Status: {alert.status}",
            f"Risk Score: {alert.risk_score}",
            f"Created: {alert.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Generated By: {generated_by.full_name or generated_by.email}",
            f"Generated At: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        ]

        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(72, height - 72, lines[0])
        pdf.setFont("Helvetica", 10)
        y = height - 110
        for line in lines[1:]:
            pdf.drawString(72, y, str(line)[:105])
            y -= 18
        pdf.save()
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes
