"""Add performance indexes

Revision ID: 16eac868be71
Revises: 0007
Create Date: 2026-05-01 19:07:30.848389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16eac868be71'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admin_otp_challenges_challenge_id_key'), 'admin_otp_challenges', type_='unique')
    op.drop_index(op.f('ix_admin_otp_challenges_challenge_id'), table_name='admin_otp_challenges')
    op.create_index(op.f('ix_admin_otp_challenges_challenge_id'), 'admin_otp_challenges', ['challenge_id'], unique=True)
    op.create_index('ix_alerts_risk_created', 'alerts', ['risk_score', 'created_at'], unique=False)
    op.create_index('ix_alerts_severity_status', 'alerts', ['severity', 'status'], unique=False)
    op.drop_index(op.f('ix_incident_alerts_alert_id'), table_name='incident_alerts')
    op.create_index('ix_normalized_logs_ip_user', 'normalized_logs', ['src_ip', 'username'], unique=False)
    op.create_index('ix_normalized_logs_severity_time', 'normalized_logs', ['severity', 'event_time'], unique=False)
    op.create_index('ix_normalized_logs_source_time', 'normalized_logs', ['source', 'event_time'], unique=False)
    op.drop_column('threat_entries', 'external_source_url')
    op.drop_column('threat_entries', 'external_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_entries', sa.Column('external_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('threat_entries', sa.Column('external_source_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_index('ix_normalized_logs_source_time', table_name='normalized_logs')
    op.drop_index('ix_normalized_logs_severity_time', table_name='normalized_logs')
    op.drop_index('ix_normalized_logs_ip_user', table_name='normalized_logs')
    op.create_index(op.f('ix_incident_alerts_alert_id'), 'incident_alerts', ['alert_id'], unique=False)
    op.drop_index('ix_alerts_severity_status', table_name='alerts')
    op.drop_index('ix_alerts_risk_created', table_name='alerts')
    op.drop_index(op.f('ix_admin_otp_challenges_challenge_id'), table_name='admin_otp_challenges')
    op.create_index(op.f('ix_admin_otp_challenges_challenge_id'), 'admin_otp_challenges', ['challenge_id'], unique=False)
    op.create_unique_constraint(op.f('admin_otp_challenges_challenge_id_key'), 'admin_otp_challenges', ['challenge_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
