"""Add additional performance indexes for critical queries

Revision ID: 2026_05_04_120000
Revises: 16eac868be71
Create Date: 2026-05-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2026_05_04_120000'
down_revision = '16eac868be71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Additional indexes for logs table
    op.create_index('ix_raw_logs_received_at', 'raw_logs', ['received_at'], unique=False)
    op.create_index('ix_raw_logs_source_received', 'raw_logs', ['source', 'received_at'], unique=False)
    op.create_index('ix_raw_logs_ip_received', 'raw_logs', ['ip_address', 'received_at'], unique=False)
    
    # Additional indexes for alerts table
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_status_created', 'alerts', ['status', 'created_at'], unique=False)
    op.create_index('ix_alerts_source_ip', 'alerts', ['normalized_log_id'], unique=False)
    
    # Indexes for audit logs table
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_created', 'audit_logs', ['entity_type', 'created_at'], unique=False)
    
    # Indexes for url scan results
    op.create_index('ix_url_scan_results_created_at', 'url_scan_results', ['created_at'], unique=False)
    op.create_index('ix_url_scan_results_status_created', 'url_scan_results', ['status', 'created_at'], unique=False)
    
    # Indexes for awareness attempts
    op.create_index('ix_awareness_attempts_user_quiz', 'awareness_attempts', ['user_id', 'quiz_id'], unique=False)
    op.create_index('ix_awareness_attempts_submitted', 'awareness_attempts', ['submitted_at'], unique=False)
    op.create_index('ix_awareness_attempts_passed', 'awareness_attempts', ['passed', 'submitted_at'], unique=False)
    
    # Indexes for IOCs table (if exists)
    try:
        op.create_index('ix_iocs_type_status', 'iocs', ['type', 'status'], unique=False)
        op.create_index('ix_iocs_reputation', 'iocs', ['reputation'], unique=False)
        op.create_index('ix_iocs_last_seen', 'iocs', ['last_seen'], unique=False)
    except Exception:
        # IOCs table might not exist yet
        pass
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop additional indexes for logs table
    op.drop_index('ix_raw_logs_received_at', table_name='raw_logs')
    op.drop_index('ix_raw_logs_source_received', table_name='raw_logs')
    op.drop_index('ix_raw_logs_ip_received', table_name='raw_logs')
    
    # Drop additional indexes for alerts table
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_status_created', table_name='alerts')
    op.drop_index('ix_alerts_source_ip', table_name='alerts')
    
    # Drop indexes for audit logs table
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_created', table_name='audit_logs')
    
    # Drop indexes for url scan results
    op.drop_index('ix_url_scan_results_created_at', table_name='url_scan_results')
    op.drop_index('ix_url_scan_results_status_created', table_name='url_scan_results')
    
    # Drop indexes for awareness attempts
    op.drop_index('ix_awareness_attempts_user_quiz', table_name='awareness_attempts')
    op.drop_index('ix_awareness_attempts_submitted', table_name='awareness_attempts')
    op.drop_index('ix_awareness_attempts_passed', table_name='awareness_attempts')
    
    # Drop indexes for IOCs table
    try:
        op.drop_index('ix_iocs_type_status', table_name='iocs')
        op.drop_index('ix_iocs_reputation', table_name='iocs')
        op.drop_index('ix_iocs_last_seen', table_name='iocs')
    except Exception:
        # IOCs table might not exist
        pass
    
    # ### end Alembic commands ###
